# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190327_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='release_date'),
        ),
    ]
