# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190327_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppublishing',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='pub_date'),
        ),
    ]
