# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190327_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppublishing',
            name='id',
        ),
        migrations.AddField(
            model_name='apppublishing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
