# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190327_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppublishing',
            old_name='user',
            new_name='customer',
        ),
    ]
